# Generated by Django 3.1.2 on 2020-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
    ]
